### ISSUE TITLE
Families not working as expexted.

### ISSUE THREAD

**Issue by highvoltaged** [magneto538/Koala#5]
I dont know what im doing wrong, but the following code puts the knobs into seemingly random families.
The knob 'slider' should go into SLIDER_FAM, etc...
This gets even more random with larger projects.
Family 0 doesn't seem to work at all.

> on init
> 	activate_logger(get_folder(GET_FOLDER_PATCH_DIR) & "/log.nka")
> 	Koala.init
> 	create_instrument(540, "", "", "Koala v2.1 - TEMPLATE SCRIPT")
> 
> 	create_family(SLIDER_FAM,0)
> 	create_family(MUTES_FAM,1)
> 	create_family(AMBISEND_FAM,2)
> 	create_family(AMBI_FAM,3)
> 
> 	create_knob(slider, SLIDER_FAM, 1, 20, 0, 1000000, 500000, 10000, PERSISTENT, $KNOB_UNIT_PERCENT, 'test')
> 	create_knob(mutes, MUTES_FAM, 1, 40, 0, 1000000, 500000, 10000, PERSISTENT, $KNOB_UNIT_PERCENT, 'test')
> 	create_knob(ambisend, AMBISEND_FAM, 1, 60, 0, 1000000, 500000, 10000, PERSISTENT, $KNOB_UNIT_PERCENT, 'test')
> 	create_knob(ambi, AMBI_FAM, 1, 80, 0, 1000000, 500000, 10000, PERSISTENT, $KNOB_UNIT_PERCENT, 'test')
> end on 
> 

Here is the compiled code:
https://www.dropbox.com/s/y25zm8o67ol2ww5/Koala%20-%20test%20SCRIPT%20COMPILED.txt?dl=0

**Comment by highvoltaged** [comment]
I have the same issue with Groupfolders

The first group folder doesnt seem to work at all, but i had an other project, where the first 6 group folders contained only the first group, where i clearly set them to different ones.

> on init
> 	activate_logger(get_folder(GET_FOLDER_PATCH_DIR) & "/log.nka")
> 	Koala.init
> 	create_instrument(540, "", "", "Koala v2.1 - TEMPLATE SCRIPT")
> 	declare i
> 
> 	create_group_folder(notworking)
> 	for i:= 0 to 5
> 		add_group_id(notworking,i)
> 	end for
> 	create_group_folder(What)
> 	for i:= 0 to 5
> 		add_group_id(What,i)
> 	end for
> 	create_group_folder(MIC_SNBLEED)
> 	for i:= 6 to 11
> 		add_group_id(MIC_SNBLEED, i)
> 	end for
> 	create_group_folder(MIC_OH1)
> 	for i:= 12 to 17
> 		add_group_id(MIC_OH1,i)
> 	end for
> 	create_group_folder(MIC_OH2)
> 	for i:= 18 to 23
> 		add_group_id(MIC_OH2, i)
> 	end for
> 	create_group_folder(MIC_OH3)
> 	for i:= 24 to 29
> 		add_group_id(MIC_OH3, i)
> 	end for
> 	create_group_folder(MIC_ROOM1)
> 	for i:= 30 to 35
> 		add_group_id(MIC_ROOM1, i)
> 	end for
> 	create_group_folder(MIC_ROOM2)
> 	for i:= 36 to 41
> 		add_group_id(MIC_ROOM2, i)
> 	end for
> end on

**Comment by simonecoen** [comment]
Yes,
I noticed that behaviour too.

I was in a hurry and ‘fixed’ it by choosing random IDs for the families… with high number counts… like:

create_family(SLIDER_FAM,10)
create_family(MUTES_FAM,21)
create_family(AMBISEND_FAM,45)
create_family(AMBI_FAM,59)
The ID, above all, never gets used apart from the creation process as far as I remember since families are always referenced by their variable name.

Cheers,

Simone Coen

**Comment by highvoltaged** [comment]
Thanks for the reply
I wrote in the numbers you provided, and it got even more random results.

The IDs  seems to be get used, cause anything i want to do with those families are referencing the wrong ones.
For example if i try to hide the family, it will hide exactly those wrong ones, that the debbugger shows.

**Comment by simonecoen** [comment]
I remember having troubles in that too.
Try and start with hiding all families and showing only the ones you want to show.

It appeared to me like there is some kind of odd persistency in the status of those families.
But once you succeed in “resetting” them they work fine each single time.

Simone Coen

**Comment by magneto538** [comment]
As per [this page](https://github.com/magneto538/Koala/wiki/3.2---Assign-a-UI-control-to-multiple-families) on the Wiki, UI Families are supposed to be used with bitmasks, not regular integers. That way, you can assign a single UI control to any of the 32 Families available and process it accordingly. You implementation is not working because you are using regular integers instead of using powers of 2 (constants `MASK.1,` `MASK.2` etc.). Assigning 0 to a Family doesn't work of course, as the bitmask of 0 is a set of zeroes.

There is a pretty extensive explanation of the correct implementation at the link provided, as well as examples and an overview on bitmasks that should help you guys getting started with it.

**Comment by highvoltaged** [comment]
Thanks! I have read the Wiki a couple of times, but it wasn't clear at all that you MUST use masks. The majority of the Wiki gives examples with integers. 

Now it works great, thanks.

But the folder grouping is still buggy here. But it could be an error in teh debugger?

It says on the groups with error: Invalid menu value (Assignment has no effect)!
the line it refets to:    $DEBUG__groups_name := search(%GRP__folders,$DEBUG__groups_folder)
